# Generated by Django 4.2.1 on 2024-11-16 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='规则名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('mertric', models.CharField(max_length=50, verbose_name='监控指标')),
                ('condition', models.CharField(max_length=50, verbose_name='监控条件')),
                ('threshold', models.FloatField(verbose_name='阈值')),
                ('severity', models.CharField(max_length=50, verbose_name='告警级别')),
                ('target', models.CharField(max_length=255, verbose_name='通知对象')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('feishuWebhook', models.CharField(max_length=255, verbose_name='飞书webhook')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interval', models.IntegerField(default=60, verbose_name='告警间隔')),
                ('lastTriggerTime', models.DateTimeField(blank=True, null=True, verbose_name='上次触发时间')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'db_table': 'alertRule',
                'ordering': ['-createTime'],
            },
        ),
        migrations.CreateModel(
            name='AlertRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50, verbose_name='监控指标')),
                ('value', models.FloatField(verbose_name='监控值')),
                ('triggerTime', models.DateTimeField(verbose_name='触发时间')),
                ('alertRule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alerts.alertrulemodel', verbose_name='告警规则')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录',
                'db_table': 'alertRecord',
                'ordering': ['-triggerTime'],
            },
        ),
    ]
