# Generated by Django 4.2.1 on 2024-11-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrulemodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='规则名称'),
        ),
        migrations.AlterField(
            model_name='alertrulemodel',
            name='severity',
            field=models.CharField(choices=[('critical', '严重'), ('warning', '警告'), ('info', '提示')], max_length=10, verbose_name='告警级别'),
        ),
    ]
