# Generated by Django 4.2.1 on 2024-11-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_menumodel_unique_together'),
        ('Alerts', '0002_alter_alertrulemodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertrulemodel',
            name='target',
        ),
        migrations.AddField(
            model_name='alertrulemodel',
            name='target',
            field=models.ManyToManyField(blank=True, null=True, related_name='alert_target', to='User.usermodel', verbose_name='告警对象'),
        ),
    ]
