# Generated by Django 4.2.1 on 2024-11-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0005_alter_alertrulemodel_feishuwebhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrulemodel',
            name='condition',
            field=models.CharField(choices=[('>', '大于'), ('=', '等于'), ('<', '小于'), ('>=', '大于等于'), ('<=', '小于等于')], max_length=10, verbose_name='监控条件'),
        ),
        migrations.AlterField(
            model_name='alertrulemodel',
            name='mertric',
            field=models.CharField(choices=[('cpu_usage', 'CPU使用率'), ('memory_usage', '内存使用率'), ('sent', '上传带宽'), ('recv', '下载带宽'), ('load', '负载'), ('score', '评分')], max_length=50, verbose_name='监控指标'),
        ),
    ]
