# Generated by Django 4.2.1 on 2024-08-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0013_alter_menumodel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='爬虫名')),
                ('nodeUid', models.UUIDField(unique=True, verbose_name='爬虫唯一标识')),
                ('resources', models.CharField(max_length=100, unique=True, verbose_name='爬虫资源路径')),
                ('status', models.BooleanField(default=True, verbose_name='节点状态')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.usermodel', verbose_name='创建人')),
            ],
        ),
    ]
