# Generated by Django 4.2.1 on 2024-08-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spider', '0002_remove_spidermodel_nodeuid_spidermodel_spideruid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spidermodel',
            name='spiderUid',
            field=models.UUIDField(unique=True, verbose_name='爬虫唯一标识'),
        ),
    ]
