# Generated by Django 4.2.1 on 2024-11-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spider', '0003_alter_spidermodel_spideruid'),
    ]

    operations = [
        migrations.AddField(
            model_name='spidermodel',
            name='command',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='启动命令'),
        ),
    ]
