# Generated by Django 4.2.1 on 2024-11-16 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spider', '0004_spidermodel_command'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spidermodel',
            options={'ordering': ['-createTime'], 'verbose_name': '爬虫', 'verbose_name_plural': '爬虫'},
        ),
        migrations.AlterModelTable(
            name='spidermodel',
            table='spider',
        ),
    ]
