# Generated by Django 4.2.1 on 2024-08-16 13:45

from django.db import migrations, models
import django.db.models.deletion
import utils.date
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0013_alter_menumodel_unique_together'),
        ('Node', '0002_rename_node_uid_nodemodel_nodeuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskUid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='任务唯一标识')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='任务名')),
                ('status', models.BooleanField(default=False, verbose_name='任务状态')),
                ('isTiming', models.BooleanField(default=False, verbose_name='是否定时')),
                ('cronExpression', models.CharField(blank=True, max_length=100, null=True, validators=[utils.date.validate_cron], verbose_name='定时任务cron表达式')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.usermodel', verbose_name='创建人')),
                ('taskNodes', models.ManyToManyField(to='Node.nodemodel', verbose_name='任务节点')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'task',
                'ordering': ['-createTime'],
            },
        ),
    ]
