# Generated by Django 4.2.1 on 2024-08-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Node', '0002_rename_node_uid_nodemodel_nodeuid_and_more'),
        ('Task', '0002_alter_taskmodel_tasknodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskNodes',
            field=models.ManyToManyField(to='Node.nodemodel', verbose_name='任务节点'),
        ),
    ]
