# Generated by Django 4.2.1 on 2024-08-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_taskmodel_tasknodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='cronExpression',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='定时任务cron表达式'),
        ),
    ]
