# Generated by Django 4.2.1 on 2024-08-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spider', '0001_initial'),
        ('Task', '0004_alter_taskmodel_cronexpression'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='taskSpiders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Spider.spidermodel', verbose_name='任务爬虫'),
            preserve_default=False,
        ),
    ]
