# Generated by Django 4.2.1 on 2024-07-07 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='uid',
            field=models.CharField(default=uuid.UUID('9b714424-004e-45e9-9ba6-f21f046e85a0'), max_length=32, unique=True, verbose_name='用户唯一标识'),
        ),
    ]
