# Generated by Django 4.2.1 on 2024-07-07 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_usermodel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionmodel',
            name='title',
            field=models.CharField(default=1, max_length=32, verbose_name='权限标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='uid',
            field=models.CharField(default=uuid.UUID('566d915f-5e22-4c6b-9808-95b940a653c5'), max_length=32, unique=True, verbose_name='用户唯一标识'),
        ),
    ]
