# Generated by Django 4.2.1 on 2024-07-07 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_permissionmodel_title_alter_usermodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=32, unique=True, verbose_name='用户唯一标识'),
        ),
    ]
