# Generated by Django 4.2.1 on 2024-07-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_permissionmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='isMenu',
            field=models.BooleanField(default=True, verbose_name='是否菜单'),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='path',
            field=models.CharField(max_length=32, verbose_name='路径'),
        ),
    ]
