# Generated by Django 4.2.1 on 2024-07-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_menumodel_ismenu_alter_menumodel_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodel',
            name='isMenu',
        ),
    ]
