# Generated by Django 4.2.1 on 2024-07-07 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_menumodel_ismenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='用户唯一标识'),
        ),
    ]
