# Generated by Django 4.2.1 on 2024-07-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_usermodel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default='2024-07-07 06:08:03.000000', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menumodel',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='permissionmodel',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default='2024-07-07 06:08:03.000000', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissionmodel',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
