# Generated by Django 4.2.1 on 2024-07-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_menumodel_createtime_menumodel_updatetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menumodel',
            options={'ordering': ['-createTime'], 'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
        migrations.AlterModelOptions(
            name='permissionmodel',
            options={'ordering': ['-createTime'], 'verbose_name': '权限', 'verbose_name_plural': '权限'},
        ),
    ]
