# Generated by Django 4.2.1 on 2024-07-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_permissionmodel_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='角色名'),
        ),
        migrations.AlterUniqueTogether(
            name='permissionmodel',
            unique_together={('method', 'path')},
        ),
    ]
