# Generated by Django 4.2.1 on 2024-07-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_rolemodel_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menumodel',
            unique_together={('name', 'path')},
        ),
    ]
