# Generated by Django 4.2.1 on 2024-08-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='节点名')),
                ('node_uid', models.UUIDField(unique=True, verbose_name='节点唯一标识')),
                ('status', models.BooleanField(default=False, verbose_name='节点状态')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
                'db_table': 'node',
                'ordering': ['-createTime'],
            },
        ),
    ]
