# Generated by Django 4.2.1 on 2024-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Node', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodemodel',
            old_name='node_uid',
            new_name='nodeUid',
        ),
        migrations.AlterField(
            model_name='nodemodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='节点状态'),
        ),
    ]
